### ISSUE TITLE
compatible with Websitebaker 2.12.2 ?

### ISSUE THREAD

**Issue by BernieO** [WebsiteBaker-modules/guestbook#1]
Is this guestbook compatible with websitebaker 2.12.2?
I have guestbook 2.7 installed - can I upgrade directly to guestbook 2.8.8 from this repo?

**Comment by mrbaseman** [comment]
This repository is just a mirror of the addons area of the WB page. From time to time I update the modules here with the content from the official download area. Given the fact that this particular module is not offered anymore on the wb page I assume that it isn't supported under the current wb version anymore, but feel free to ask this question in the wb forum, too.

**Comment by BernieO** [comment]
OK. Thanks

**Comment by BernieO** [comment]
Sorry - I just now discovered that there are several successors of Websitebaker 2.8.3, which are:
- Websitebaker 2.12.2 (https://websitebaker.org)
- Lepton CMS (https://lepton-cms.org
- WBCE CMS (https://wbce.org)

I assume now that these addons are for WBCE? Is this correct?

Sorry for the reopening - I lost websitebaker a bit out of sight and didn‘t follow the development the last couple of years. Now I want to upgrade to a more recent version and I am not sure yet which road to follow...

**Comment by mrbaseman** [comment]
The core team of WebsiteBaker has continued developing new versions of the CMS core system. There were several service packs for WB 2.8.3, the version 2.9 was skipped because there has been an attempt to rewrite large parts of the code earlier, then there was 2.10, 2.11, and finally 2.12 for which the current patch release is 2.12.2, as you have already found out.

I believe Lepton CMS has been forked earlier (it was already there, when I started using WB 2.8.3, so maybe it was forked from 2.8.2 - or even earlier).

WBCE was forked from 2.8.3 sp3 I think, and developed independently. The latest version there is 1.4.0. 

As I said, the modules in this github account are a "mirror" of the [official WB addons repo](https://addon.websitebaker.org). From time to time I download all the modules and copy them into the corresponding github repository. There are a few exceptions, namely the ones that I maintain. For those modules I have my own private repository and I publish them here. When I announce the new releases, someone with the permission to update the WB addons area uploads them there subsequently.

Most modules are still compatible with WB and with WBCE. For the ones that I maintain, I try to keep them up for both core systems, but not all features are available everywhere. I need to put in a few checks for the features of the core, and depending on their availability I can switch on features in the modules.

About upgrading: Both, WB and WBCE support upgrading from 2.8.3 to the latest version. For WB I'm not sure if you have to take an intermediate step, but I think it's possible in one step now. About Lepton I'm not sure to which extent upgrading is possible. Anyhow, you should check the upgrading guide of the core distribution of your choice, and usually to check the modules for compatibility is a separate story.

**Comment by BernieO** [comment]
Thank you very much for the detailed explanation. That helps a lot‘
